/// defines the network layer (OSI model) for a method
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[allow(dead_code)]
pub enum NetworkLayer {
    Application,
    Presentation,
    Session,
    Transport,
    Network,
    DataLink,
    Physical,
}

impl NetworkLayer {
    pub fn name(&self) -> &'static str {
        match self {
            NetworkLayer::Application => "L7 Application",
            NetworkLayer::Presentation => "L6 Presentation",
            NetworkLayer::Session => "L5 Session",
            NetworkLayer::Transport => "L4 Transport",
            NetworkLayer::Network => "L3 Network",
            NetworkLayer::DataLink => "L2 Data Link",
            NetworkLayer::Physical => "L1 Physical",
        }
    }
    #[allow(dead_code)]
    pub fn short_name(&self) -> &'static str {
        match self {
            NetworkLayer::Application => "App",
            NetworkLayer::Presentation => "Pres",
            NetworkLayer::Session => "Sess",
            NetworkLayer::Transport => "Trans",
            NetworkLayer::Network => "Net",
            NetworkLayer::DataLink => "DL",
            NetworkLayer::Physical => "PHY",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TransportType {
    Tcp,
    Udp,
    Icmp,
    Raw,
    Hybrid,
}

impl TransportType {
    pub fn name(&self) -> &'static str {
        match self {
            TransportType::Tcp => "TCP",
            TransportType::Udp => "UDP",
            TransportType::Icmp => "ICMP",
            TransportType::Raw => "Raw",
            TransportType::Hybrid => "Hybrid",
        }
    }
}

/// A single amplification / attack method
#[derive(Debug, Clone)]
pub struct AmplificationMethod {
    pub id: &'static str,
    pub name: &'static str,
    pub description: &'static str,
    pub layer: NetworkLayer,
    pub transport: TransportType,
    pub port: u16,
    pub ampl_factor: &'static str,
    pub needs_root: bool,
    pub works_with_tor: bool,
    pub is_implemented: bool,
    /// If this is one of the existing HTTP modes, the AttackMode variant (lowercase)
    pub http_mode: Option<&'static str>,
}

/// The full catalog of all known amplification methods
pub static METHODS: &[AmplificationMethod] = &[
    // ================================================================
    // L7 APPLICATION — HTTP (existing 88 modes grouped by category)
    // ================================================================
    AmplificationMethod {
        id: "http-bandwidth",
        name: "HTTP Bandwidth Exhaustion",
        description: "Sends maximum-sized requests to saturate bandwidth. Uses large payloads, multipart forms, and oversized headers to consume all available pipe capacity. Simple but effective when multiplied across many connections.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 80,
        ampl_factor: "1-5x per request (aggregate)",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: Some("bandwidth"),
    },
    AmplificationMethod {
        id: "http-slow-read",
        name: "HTTP Slow Read (Slowloris variant)",
        description: "Opens connections and reads the response extremely slowly (1 byte at a time with long delays). Keeps server connection pools occupied, preventing new legitimate connections from being accepted. Works by advertising a tiny TCP window.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 80,
        ampl_factor: "Connection exhaustion (not bandwidth)",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: Some("slowread"),
    },
    AmplificationMethod {
        id: "http-image-opt",
        name: "HTTP Image Optimization Abuse",
        description: "Targets image processing endpoints with requests for oversized images or complex transformations. Forces the server to allocate memory and CPU for image processing/optimization on every request. High CPU amplification per request.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 80,
        ampl_factor: "10-50x CPU vs response size",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: Some("imageopt"),
    },
    AmplificationMethod {
        id: "http-large-post",
        name: "HTTP Large POST Body",
        description: "Sends POST requests with extremely large bodies (multi-megabyte JSON, XML, or form data). Server must parse, validate, and allocate memory for the entire payload. Memory and CPU exhaustion vector.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 80,
        ampl_factor: "5-20x request/response ratio",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: Some("largepost"),
    },
    AmplificationMethod {
        id: "http-asset-spray",
        name: "HTTP Asset Spray",
        description: "Requests many different static assets (JS, CSS, images) simultaneously. Forces the server to open files, read from disk, and serve each one. Combined with cache-busting, bypasses CDN caching and hits origin servers.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 80,
        ampl_factor: "2-10x (many small files)",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: Some("assetspray"),
    },
    AmplificationMethod {
        id: "http-range-request",
        name: "HTTP Range Request Bomb",
        description: "Sends requests with overlapping byte ranges (Range: bytes=0-, 0-1, 0-2, etc.). Server must parse ranges, validate boundaries, and potentially serve the same content multiple times. Some servers decompress content for each range.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 80,
        ampl_factor: "2-10x",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: Some("rangereq"),
    },
    AmplificationMethod {
        id: "http-cookie-bomb",
        name: "HTTP Cookie Bomb (Large Cookies)",
        description: "Sends requests with many large cookies (overall >8KB). Each request forces the server to parse, validate, and store cookie headers in memory. Combined with session tracking, this can exhaust backend storage and processing.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 80,
        ampl_factor: "3-8x per request",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: Some("cookiebomb"),
    },
    AmplificationMethod {
        id: "http-ssr-abuse",
        name: "HTTP SSR/SSRF Abuse",
        description: "Sends requests designed to trigger server-side rendering or server-side include processing. Forces template evaluation, database queries, and internal network requests from the server. High CPU/server-load amplification per request.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 80,
        ampl_factor: "10-100x (if SSR triggered)",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: Some("ssr"),
    },
    AmplificationMethod {
        id: "http-middleware-chain",
        name: "HTTP Middleware Chain Abuse",
        description: "Sends requests that trigger many middleware layers (auth, rate-limit, logging, caching, validation). Forces the server to run its full middleware pipeline for each request, multiplying CPU cost. Particularly effective against serverless/edge platforms.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 80,
        ampl_factor: "3-20x per request",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: Some("middleware"),
    },
    AmplificationMethod {
        id: "http-request-flood",
        name: "HTTP Request Flood",
        description: "Sends many rapid-fire HTTP requests as fast as possible. Pure volumetric attack exhausting connection slots, file descriptors, and event loop capacity. The baseline HTTP flooding technique.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 80,
        ampl_factor: "1x (pure volume)",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: Some("requestflood"),
    },
    AmplificationMethod {
        id: "http-404-storm",
        name: "HTTP 404 Storm",
        description: "Requests many random non-existent URLs. Forces the server to process routing logic, log misses, and return 404 pages. Some frameworks generate full error pages for every miss, increasing response size and CPU cost.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 80,
        ampl_factor: "2-5x",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: Some("notfound"),
    },
    AmplificationMethod {
        id: "http-slowloris",
        name: "HTTP Slowloris",
        description: "The classic Slowloris attack. Opens connections and sends partial HTTP headers very slowly, never completing the request. Server connection pools fill up with half-open connections, eventually refusing new connections.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 80,
        ampl_factor: "Connection pool exhaustion",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: Some("slowloris"),
    },
    AmplificationMethod {
        id: "http-header-bomb",
        name: "HTTP Header Bomb",
        description: "Sends requests with many custom HTTP headers (30+ headers per request). Each header requires tokenization, validation, and storage. Combined with large header values, this exhausts server header buffer limits and CPU.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 80,
        ampl_factor: "3-10x per request",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: Some("headerbomb"),
    },
    AmplificationMethod {
        id: "http-query-flood",
        name: "HTTP Query String Flood",
        description: "Sends requests with many query parameters (50-200 params). Server must parse the entire query string, validate parameter names/values, and store them. Combined with database-backed sessions, each param lookup adds overhead.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 80,
        ampl_factor: "2-5x per request",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: Some("queryflood"),
    },
    AmplificationMethod {
        id: "http-deep-path",
        name: "HTTP Deep Path Traversal",
        description: "Requests URLs with very deep paths (/a/b/c/.../z repeated many times). Server must parse and normalize the path, check routing at each level, and potentially access filesystem or database for each segment.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 80,
        ampl_factor: "3-15x per request",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: Some("deeppath"),
    },
    AmplificationMethod {
        id: "http-auth-flood",
        name: "HTTP Authentication Flood",
        description: "Sends requests with Authorization headers, forcing server to decode, validate, and check credentials against its auth backend (database, LDAP, OAuth provider). Each request triggers authentication processing that is CPU-intensive.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 80,
        ampl_factor: "10-100x vs unauthenticated",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: Some("authflood"),
    },
    AmplificationMethod {
        id: "http-cache-bypass",
        name: "HTTP Cache Bypass",
        description: "Sends requests with unique query parameters or varying headers to bypass CDN/caching layers. Every request hits the origin server directly, multiplying the effective traffic. Combined with asset requests, causes origin overload.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 80,
        ampl_factor: "5-50x (cache bypass multiplier)",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: Some("cachebypass"),
    },
    AmplificationMethod {
        id: "http-form-multi",
        name: "HTTP Multipart Form Flood",
        description: "Sends POST requests with multipart/form-data containing many fields and large file parts. Server must parse MIME boundaries, decode each part, validate content types, and potentially process file uploads. Memory-intensive per request.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 80,
        ampl_factor: "5-20x per request",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: Some("formmulti"),
    },
    AmplificationMethod {
        id: "http-xml-bomb",
        name: "HTTP XML Bomb (Billion Laughs)",
        description: "Sends XML payloads with entity expansion attacks (e.g., the Billion Laughs attack). XML parser expands nested entities exponentially, consuming massive memory. A few hundred bytes of XML can expand to gigabytes of in-memory representation.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 80,
        ampl_factor: "1M+ (theoretical unlimited expansion)",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: Some("xmlbomb"),
    },
    AmplificationMethod {
        id: "http-graphql-flood",
        name: "HTTP GraphQL Query Flood",
        description: "Sends complex nested GraphQL queries that trigger recursive database lookups and joins. A single query can trigger dozens of database queries. Combined with batching, amplifies backend database load dramatically.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 80,
        ampl_factor: "10-100x per query",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: Some("graphqlflood"),
    },
    AmplificationMethod {
        id: "http-redirect-loop",
        name: "HTTP Redirect Loop",
        description: "Sends requests that trigger server-side redirect chains. Each redirect requires the server to process the redirect logic, build response headers, and handle the redirected request internally. Multiplies server processing per client request.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 80,
        ampl_factor: "2-10x per request",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: Some("redirectloop"),
    },
    AmplificationMethod {
        id: "http-keepalive-flood",
        name: "HTTP Keep-Alive Flood",
        description: "Uses HTTP Keep-Alive connections to send a high volume of requests over a single TCP connection over an extended period. Bypasses per-connection rate limits while maintaining persistent server resource allocation.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 80,
        ampl_factor: "2-5x per connection",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: Some("keepaliveflood"),
    },
    AmplificationMethod {
        id: "http-upgrade-flood",
        name: "HTTP Upgrade Header Amplify",
        description: "Sends requests with Upgrade headers (WebSocket, HTTP/2, etc.) forcing the server to negotiate protocol upgrades. Each upgrade negotiation requires additional handshake processing, delaying response and consuming server resources.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 80,
        ampl_factor: "2-8x per request",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: Some("upgradeamplify"),
    },
    AmplificationMethod {
        id: "http-connection-close",
        name: "HTTP Connection: Close Flood",
        description: "Sends requests with Connection: close headers, preventing HTTP keep-alive. Forces the server to tear down and recreate TCP connections for each request. Multiplies TCP handshake overhead on the server.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 80,
        ampl_factor: "2-3x per request (TCP overhead)",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: Some("connectionclose"),
    },
    AmplificationMethod {
        id: "http-vary-flood",
        name: "HTTP Vary Header Abuse",
        description: "Sends requests with varying Accept-Encoding, Accept-Language, and other Vary-relevant headers. Forces the server to cache or generate different variants of the same content, fragmenting the cache and increasing storage/computation.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 80,
        ampl_factor: "3-15x (cache fragmentation)",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: Some("varyflood"),
    },
    AmplificationMethod {
        id: "http-slow-post",
        name: "HTTP Slow POST",
        description: "Sends a POST with Content-Length header claiming a large body, but sends the body very slowly (a few bytes at a time). Server allocates buffer space and waits for the full body, tying up connection slots for extended periods.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 80,
        ampl_factor: "Connection timeout exhaustion",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: Some("slowpost"),
    },
    AmplificationMethod {
        id: "http-csp-report",
        name: "HTTP CSP Report Flood",
        description: "Sends POST requests to Content-Security-Policy report-uri endpoints. Each request contains a crafted CSP violation report that the server must parse, validate, and log. Many CSP endpoints lack rate limiting.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 80,
        ampl_factor: "2-5x per report",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: Some("cspreports"),
    },
    AmplificationMethod {
        id: "http-json-bomb",
        name: "HTTP JSON Bomb",
        description: "Sends deeply nested JSON payloads (arrays within arrays, deeply nested objects). JSON parser must recursively parse the entire structure, causing stack depth and memory allocation issues. Similar to XML bomb but for JSON endpoints.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 80,
        ampl_factor: "10-100x",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: Some("jsonbomb"),
    },
    AmplificationMethod {
        id: "http-prototype-pollution",
        name: "HTTP Prototype Pollution Flood",
        description: "Sends requests with __proto__, constructor.prototype, or similar JavaScript prototype pollution payloads. Targets Node.js applications, forcing prototype pollution detection or vulnerable parsing code execution. CPU-intensive for some frameworks.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 80,
        ampl_factor: "5-20x per request",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: Some("prototypeflood"),
    },
    AmplificationMethod {
        id: "http-csv-bomb",
        name: "HTTP CSV/Formula Injection Bomb",
        description: "Sends POST requests with CSV data containing formula injection payloads (=CMD, +DDE, etc.). Server-side CSV processors may evaluate formulas, triggering compute operations. Combined with large CSV files, amplifies memory usage.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 80,
        ampl_factor: "5-30x per request",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: Some("csvbomb"),
    },
    // Grouped summary entries for the remaining HTTP modes
    AmplificationMethod {
        id: "http-method-variants",
        name: "HTTP Method Variant Flood (HEAD/OPTIONS/PATCH/CONNECT/DELETE)",
        description: "Uses non-GET/POST HTTP methods (HEAD, OPTIONS, PATCH, CONNECT, DELETE, PUT, TRACE) that may be less optimized on the server. Each method triggers different code paths, often with unexpected resource consumption.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 80,
        ampl_factor: "2-10x per non-standard method",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: Some("normal"),
    },
    AmplificationMethod {
        id: "http-edge-timing",
        name: "HTTP Edge & Timing Attacks (Expect, Chunked, Trailers, Deflate)",
        description: "Uses HTTP edge-case features: Expect:100-continue forces server to wait for body, Chunked encoding with infinite chunks, Trailing headers that must be buffered, and Deflate/decompression bombs that expand dramatically when decoded.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 80,
        ampl_factor: "2-500x (deflate bomb can be extreme)",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: Some("normal"),
    },
    AmplificationMethod {
        id: "http-session-flood",
        name: "HTTP Session & Auth Flood (Session, Login, JWT, CSRF)",
        description: "Floods session-management endpoints. Each request forces server-side session creation, token validation, database lookups for JWT decoding, and CSRF token verification. High backend amplification against stateful endpoints.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 80,
        ampl_factor: "5-50x per request",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: Some("normal"),
    },
    AmplificationMethod {
        id: "http-api-discovery",
        name: "HTTP API Discovery & Enumeration (GraphQL Introspect, Admin, Swagger, Well-Known)",
        description: "Probes for API documentation endpoints (GraphQL introspection, Swagger UI, well-known URIs, admin panels). Forces server to generate schema responses, which can be very large. Also used as a reconnaissance-amplification combo.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 80,
        ampl_factor: "10-100x response size ratio",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: Some("normal"),
    },
    AmplificationMethod {
        id: "http-encoding-variants",
        name: "HTTP Encoding Variant Flood (TE, Want-Digest, Content-Negotiate, Save-Data, Sec-Fetch)",
        description: "Sends requests with specialized HTTP headers for content negotiation and encoding directives. Each header forces server-side processing: TE parsing, digest computation, content-type negotiation, and client hint processing.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 80,
        ampl_factor: "2-8x per request",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: Some("normal"),
    },
    AmplificationMethod {
        id: "http-serialized-bomb",
        name: "HTTP Serialized Bomb (YAML/Java/PHP deserialization)",
        description: "Sends serialized payloads designed to trigger deep or recursive deserialization. Java YAML, PHP unserialize, or similar formats that expand into complex object graphs during deserialization. Memory and CPU amplification.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 80,
        ampl_factor: "10-500x",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: Some("serializedbomb"),
    },
    AmplificationMethod {
        id: "http-graphql-batch",
        name: "HTTP GraphQL Batching Amplify",
        description: "Abuses GraphQL batching to pack many queries into a single HTTP request. A single request can trigger hundreds of separate database queries via GraphQL aliases and batched queries. Multiplies backend load per connection.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 80,
        ampl_factor: "10-200x per request",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: Some("graphqlbatch"),
    },
    AmplificationMethod {
        id: "http-webhook-flood",
        name: "HTTP Webhook/Callback Flood",
        description: "Floods webhook endpoints with many events. If the webhook triggers subsequent requests (to other services, email sends, SMS), each incoming request amplifies into multiple outgoing requests. Chains amplification.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 80,
        ampl_factor: "3-50x per webhook event",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: Some("webhookflood"),
    },
    AmplificationMethod {
        id: "http-sitemap-flood",
        name: "HTTP Sitemap/Large Response Flood",
        description: "Requests large response-generating endpoints (sitemap.xml, full RSS feeds, un-paginated API responses). Forces server to gather and serialize large datasets. Response-to-request size ratio can be very high.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 80,
        ampl_factor: "10-1000x response/request ratio",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: Some("sitemapflood"),
    },
    AmplificationMethod {
        id: "http-unicode-path",
        name: "HTTP Unicode/Encoding Path Flood",
        description: "Sends requests with Unicode-encoded, percent-encoded, and UTF-8 BOM-prefixed paths. Server must normalize, decode, and canonicalize each path variation. Multiplies routing overhead per request.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 80,
        ampl_factor: "2-5x per request",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: Some("unicodeflood"),
    },
    AmplificationMethod {
        id: "http-cache-buster",
        name: "HTTP Cache Buster Flood",
        description: "Sends requests with unique cache-busting query parameters (?v=timestamp) or headers, ensuring every request misses CDN/edge cache. Forces origin server to generate fresh responses for every request, even for static assets.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 80,
        ampl_factor: "5-50x (bypass cache multiplier)",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: Some("cachebusterflood"),
    },
    AmplificationMethod {
        id: "http-file-enum",
        name: "HTTP File Enumeration Flood",
        description: "Requests common file paths (robots.txt, .env, backup.sql, config.php, etc.) that may trigger 403/404 processing or expose large files. Mixed with dictionary-style path enumeration for maximum file-access overhead.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 80,
        ampl_factor: "2-10x per request",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: Some("fileenumflood"),
    },
    AmplificationMethod {
        id: "http-soap-flood",
        name: "HTTP SOAP/XML-RPC Flood",
        description: "Floods SOAP web service endpoints with large XML payloads. SOAP requires XML parsing, namespace resolution, WSDL validation, and potentially complex business logic execution. Each XML request is computationally expensive.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 80,
        ampl_factor: "5-30x per request",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: Some("soapflood"),
    },
    AmplificationMethod {
        id: "http-signed-header",
        name: "HTTP Signed Header/AWS SigV4 Flood",
        description: "Sends requests with signed authorization headers (AWS Signature V4, HMAC, JWT). Forces server to validate cryptographic signatures, which involves hashing, timestamp checking, and credential lookup. CPU-intensive per request.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 80,
        ampl_factor: "10-50x CPU per request",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: Some("signedheaderflood"),
    },
    AmplificationMethod {
        id: "http-header-order",
        name: "HTTP Header Order Fuzzing",
        description: "Sends requests with headers in unusual or duplicate orderings. Forces server header parsing code to handle edge cases in RFC compliance. Some servers have quadratic or exponential parsing behavior with duplicate headers.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 80,
        ampl_factor: "2-5x per request",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: Some("headerorderflood"),
    },
    AmplificationMethod {
        id: "http-referer-flood",
        name: "HTTP Referer/Cross-Domain Flood",
        description: "Sends requests with spoofed Referer and Origin headers from many different domains. Forces server CORS validation, referer-based access control checks, and cross-origin policy enforcement. Amplifies processing for each domain variation.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 80,
        ampl_factor: "2-10x per request",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: Some("refererflood"),
    },
    // ================================================================
    // L7 APPLICATION — TCP Protocols (non-HTTP)
    // ================================================================
    AmplificationMethod {
        id: "smtp-vrfy-flood",
        name: "SMTP VRFY/EXPN Flood",
        description: "Sends many SMTP VRFY and EXPN commands to open mail servers. Each command forces the server to check whether a mailbox exists, often requiring filesystem or database lookups. EXPN expands mailing lists, returning many recipients.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 25,
        ampl_factor: "2-10x per command",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "smtp-rcpt-flood",
        name: "SMTP RCPT TO Flood",
        description: "Sends many RCPT TO commands within a single SMTP session. Each recipient validation forces the server to check mailbox existence, quotas, and routing. Can fill server log files with address verification attempts.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 25,
        ampl_factor: "1-5x per recipient",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "smtp-data-bomb",
        name: "SMTP DATA Body Bomb",
        description: "Sends email messages with extremely large body content (multi-megabyte attachments or multi-recipient headers). Server must process, quarantine-scan, and store the entire message. Memory and disk amplification.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 25,
        ampl_factor: "5-50x storage amplification",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "ssh-auth-flood",
        name: "SSH Authentication Flood",
        description: "Opens many SSH connections and sends authentication attempts (password, public key, keyboard-interactive). Each attempt requires the SSH daemon to validate credentials, fork processes, and log the attempt. CPU-intensive auth per connection.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 22,
        ampl_factor: "5-20x CPU per attempt",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "ssh-kexinit-flood",
        name: "SSH KEXINIT Flood",
        description: "Opens SSH connections and sends many KEXINIT (key exchange initiation) messages. Forces the SSH server to perform expensive cryptographic key exchange calculations (Diffie-Hellman, ECDH) for each connection. Very high CPU cost.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 22,
        ampl_factor: "50-200x CPU per connection",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "ftp-port-bounce",
        name: "FTP PORT Command Bounce",
        description: "Abuses the FTP PORT command to trick the server into opening connections to a third-party target. A single FTP server can be used to scan/attack other hosts. Classic FTP bounce amplification.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 21,
        ampl_factor: "1-10x per bounce",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "ftp-listing-flood",
        name: "FTP Directory Listing Flood",
        description: "Opens many FTP connections and requests large directory listings (LIST -laR, recursive listings). Server must traverse directories, stat files, and generate listing output. Memory and I/O amplification for large directories.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 21,
        ampl_factor: "5-50x response/request ratio",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "telnet-negotiation-flood",
        name: "Telnet Negotiation Flood",
        description: "Opens Telnet sessions and sends many DO/DONT/WILL/WONT negotiation sequences. Each negotiation forces the server to respond with terminal characteristic settings. Combined with large window sizes, creates sustained traffic.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 23,
        ampl_factor: "2-5x per negotiation",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "imap-login-flood",
        name: "IMAP LOGIN/AUTH Flood",
        description: "Floods IMAP servers with LOGIN and AUTHENTICATE commands. Each login attempt forces authentication processing, mailbox locking, and logging. Combined with CRAM-MD5 or DIGEST-MD5, adds CPU-intensive authentication.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 143,
        ampl_factor: "5-15x per login attempt",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "pop3-login-flood",
        name: "POP3 USER/PASS Flood",
        description: "Floods POP3 servers with USER and PASS commands. Each authentication attempt forces mailbox lookup and validation. Simple but effective against servers without rate limiting on authentication.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 110,
        ampl_factor: "3-10x per attempt",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "ldap-search-flood",
        name: "LDAP Search Request Flood",
        description: "Sends crafted LDAP search queries to directory servers. Complex filters and wildcard searches can trigger extensive directory tree traversal and database lookups. Amplification comes from server-side search processing.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 389,
        ampl_factor: "5-30x per search",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "mqtt-connect-flood",
        name: "MQTT CONNECT Flood",
        description: "Floods MQTT brokers with CONNECT messages. Each connection forces broker session creation, topic subscription setup, and keep-alive monitoring. Combined with many client IDs, exhausts broker connection tables.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 1883,
        ampl_factor: "3-10x per connection",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "xmpp-stream-flood",
        name: "XMPP Stream Initiation Flood",
        description: "Opens many XMPP streams with <stream:stream> tags. Each stream initiation triggers XML parsing, feature negotiation, TLS start, and SASL authentication. High CPU/connection overhead on the XMPP server.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 5222,
        ampl_factor: "10-30x per stream",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "rtsp-describe-flood",
        name: "RTSP DESCRIBE/SETUP Flood",
        description: "Sends many RTSP DESCRIBE and SETUP requests to media servers. Each request forces server to describe media streams, allocate resources for potential streaming, and parse SDP descriptions. Amplifies media server processing.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 554,
        ampl_factor: "5-20x per request",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "modbus-tcp-flood",
        name: "Modbus TCP Flood",
        description: "Sends many Modbus TCP read/write requests to industrial control systems. Each request forces PLC/RTU processing for register access. While not high-bandwidth amplification, it can disrupt industrial processes.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 502,
        ampl_factor: "1-3x per request (process disruption)",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "ssl-renegotiation",
        name: "SSL/TLS Renegotiation Amplification",
        description: "Opens a TLS connection and repeatedly requests renegotiation. Each renegotiation requires the server to perform expensive asymmetric crypto operations (RSA, ECDHE key exchange). A single TCP connection can trigger 100+ renegotiations. CPU cost ratio ~100:1 vs normal connection.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 443,
        ampl_factor: "50-200x CPU amplification",
        needs_root: false,
        works_with_tor: false,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "socks-connect-flood",
        name: "SOCKS Proxy CONNECT Flood",
        description: "Floods SOCKS proxies with CONNECT requests to arbitrary targets. Each request forces the proxy to resolve DNS, open a TCP connection to the target, and relay traffic. Exhausts proxy connection capacity.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 1080,
        ampl_factor: "2-5x per connection",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "finger-query-flood",
        name: "Finger Query Flood",
        description: "Sends many queries to the Finger protocol (port 79). Each @host query can trigger the finger server to query remote hosts, creating amplification chains. Also a reconnaissance vector.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 79,
        ampl_factor: "2-5x per query",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: None,
    },
    // ================================================================
    // L7 APPLICATION — UDP Reflection/Amplification
    // ================================================================
    AmplificationMethod {
        id: "dns-amplification",
        name: "DNS Amplification (ANY/DNSSEC)",
        description: "Sends small (~60B) DNS queries with spoofed source IP to open resolvers. Response with DNSSEC records or ANY query is typically ~3000-4000B. Most common amplification vector. Mitigated by BCP38 and resolver ACLs.",
        layer: NetworkLayer::Application,
        transport: TransportType::Udp,
        port: 53,
        ampl_factor: "28-70x",
        needs_root: true,
        works_with_tor: false,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "dns-any-query",
        name: "DNS ANY Query Amplification",
        description: "Sends DNS ANY type queries to open resolvers. The ANY response includes all record types for a domain, making it typically larger than specific-type queries. Classic amplification technique.",
        layer: NetworkLayer::Application,
        transport: TransportType::Udp,
        port: 53,
        ampl_factor: "20-50x",
        needs_root: true,
        works_with_tor: false,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "dns-dnssec-query",
        name: "DNS DNSSEC Amplification",
        description: "Sends DNS queries with DNSSEC OK (DO) bit set or requesting DNSSEC record types (RRSIG, DNSKEY, NSEC). DNSSEC-signed responses are typically 4-10x larger than unsigned responses due to cryptographic signature records.",
        layer: NetworkLayer::Application,
        transport: TransportType::Udp,
        port: 53,
        ampl_factor: "40-70x",
        needs_root: true,
        works_with_tor: false,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "ntp-monlist",
        name: "NTP Monlist Amplification",
        description: "Sends a small NTP MON_GETLIST or MON_GETLIST_1 command to a vulnerable NTP server. The server responds with a list of the last 600 clients. Response can be 100x the request size. Patched in most servers since 2014, but legacy servers remain.",
        layer: NetworkLayer::Application,
        transport: TransportType::Udp,
        port: 123,
        ampl_factor: "556-750x",
        needs_root: true,
        works_with_tor: false,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "ntp-readvar",
        name: "NTP READVAR/READLIST Amplification",
        description: "Sends NTP READVAR or READLIST commands to get server configuration variables. Returned variable list can be very long for verbose NTP servers. 20-50x amplification factor.",
        layer: NetworkLayer::Application,
        transport: TransportType::Udp,
        port: 123,
        ampl_factor: "20-50x",
        needs_root: false,
        works_with_tor: false,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "snmp-getbulk",
        name: "SNMPv2 GetBulk Amplification",
        description: "Sends SNMPv2 GetBulkRequest with large max-repetitions value. The server returns many OID values in a single response. With a large MIB, response size can reach 50-60KB. 6-60x amplification factor.",
        layer: NetworkLayer::Application,
        transport: TransportType::Udp,
        port: 161,
        ampl_factor: "6-60x",
        needs_root: true,
        works_with_tor: false,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "memcached-stats",
        name: "Memcached Stats Amplification",
        description: "Sends a small (15B) 'stats' command to an exposed Memcached server. The server responds with its full cache statistics, typically ~4KB. With no authentication by default, Memcached is the highest-known amplification vector.",
        layer: NetworkLayer::Application,
        transport: TransportType::Udp,
        port: 11211,
        ampl_factor: "10,000-51,000x",
        needs_root: true,
        works_with_tor: false,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "ssdp-msearch",
        name: "SSDP M-SEARCH Amplification",
        description: "Sends a small SSDP M-SEARCH discovery request to UPnP devices on UDP port 1900. Each device responds with its full device/service description (XML), typically 2-7KB. Residential IoT devices are common reflectors.",
        layer: NetworkLayer::Application,
        transport: TransportType::Udp,
        port: 1900,
        ampl_factor: "30-75x",
        needs_root: true,
        works_with_tor: false,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "cldap-search",
        name: "CLDAP Search Amplification",
        description: "Sends a small Connectionless LDAP (CLDAP) search request to domain controllers. The search response (rootDSE or specific attribute queries) can be much larger than the request. 40-60x amplification.",
        layer: NetworkLayer::Application,
        transport: TransportType::Udp,
        port: 389,
        ampl_factor: "40-60x",
        needs_root: true,
        works_with_tor: false,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "chargen-amplification",
        name: "CharGen Amplification",
        description: "Connects to the Character Generator service (chargen, UDP port 19). The server sends a continuous stream of arbitrary characters for each received datagram. No authentication, very easy to amplify.",
        layer: NetworkLayer::Application,
        transport: TransportType::Udp,
        port: 19,
        ampl_factor: "358x",
        needs_root: true,
        works_with_tor: false,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "coap-amplification",
        name: "CoAP GET Amplification",
        description: "Sends crafted CoAP GET requests to UDP-enabled IoT devices using the Constrained Application Protocol. Large resources (firmware manifests, device configs) can produce responses 20-50x the request size.",
        layer: NetworkLayer::Application,
        transport: TransportType::Udp,
        port: 5683,
        ampl_factor: "20-50x",
        needs_root: true,
        works_with_tor: false,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "mdns-query",
        name: "mDNS Query Amplification",
        description: "Sends mDNS queries to multicast DNS responders on a local network. A single query can trigger responses from multiple devices, each with full SRV/TXT/AAAA records. Amplification via many responses per query.",
        layer: NetworkLayer::Application,
        transport: TransportType::Udp,
        port: 5353,
        ampl_factor: "2-10x per device",
        needs_root: true,
        works_with_tor: false,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "netbios-ns",
        name: "NetBIOS Name Service Amplification",
        description: "Sends NetBIOS Name Service (NBNS) status queries to Windows machines. The server responds with its name table, MAC address, and service list. Outdated but effective against legacy Windows networks.",
        layer: NetworkLayer::Application,
        transport: TransportType::Udp,
        port: 137,
        ampl_factor: "3-5x",
        needs_root: true,
        works_with_tor: false,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "portmap-dump",
        name: "RPC Portmap Dump Amplification",
        description: "Sends a DUMP request to the RPC portmapper (rpcbind). The server responds with the full list of registered RPC services and their program numbers/versions. Response size depends on number of registered services.",
        layer: NetworkLayer::Application,
        transport: TransportType::Udp,
        port: 111,
        ampl_factor: "7-28x",
        needs_root: true,
        works_with_tor: false,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "tftp-read",
        name: "TFTP Read Request Amplification",
        description: "Sends TFTP read requests (RRQ) for large files to TFTP servers. Response is the file content, which can be arbitrarily large. Minimal amplification factor but commonly available on network devices.",
        layer: NetworkLayer::Application,
        transport: TransportType::Udp,
        port: 69,
        ampl_factor: "2-4x",
        needs_root: true,
        works_with_tor: false,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "sip-options",
        name: "SIP OPTIONS Amplification",
        description: "Sends SIP OPTIONS requests to VoIP servers. Response includes full server capabilities, supported methods, and SIP extensions. Can be 10-30x larger than the request. SIP INVITE can also trigger call processing.",
        layer: NetworkLayer::Application,
        transport: TransportType::Udp,
        port: 5060,
        ampl_factor: "10-30x",
        needs_root: true,
        works_with_tor: false,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "qotd-amplification",
        name: "QOTD Quote of the Day Amplification",
        description: "Sends a small UDP datagram to the QOTD service (Quote of the Day, port 17). The server responds with a random quote, typically 100-500 bytes. Simple but effective amplification.",
        layer: NetworkLayer::Application,
        transport: TransportType::Udp,
        port: 17,
        ampl_factor: "140x",
        needs_root: true,
        works_with_tor: false,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "ws-discovery",
        name: "WS-Discovery Probe Amplification",
        description: "Sends a WS-Discovery Probe message to UDP port 3702. Each device on the network responds with its full device metadata (XML SOAP envelope). Particularly effective on networks with many Windows/bonjour devices.",
        layer: NetworkLayer::Application,
        transport: TransportType::Udp,
        port: 3702,
        ampl_factor: "25-100x",
        needs_root: true,
        works_with_tor: false,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "rip-query",
        name: "RIP Routing Update Amplification",
        description: "Sends RIPv1 request to routing devices. The server responds with its full routing table. Each route entry is 20 bytes; large routing tables produce large responses. Disrupts routing operations.",
        layer: NetworkLayer::Application,
        transport: TransportType::Udp,
        port: 520,
        ampl_factor: "5-10x",
        needs_root: true,
        works_with_tor: false,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "redis-slaveread",
        name: "Redis SLAVEOF/MIGRATE Amplification",
        description: "Sends crafted Redis commands (SLAVEOF, MIGRATE, DEBUG) to exposed Redis servers. These can trigger outbound connections or large memory dumps. No authentication by default in older versions.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 6379,
        ampl_factor: "10-100x",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "mongodb-ismaster",
        name: "MongoDB isMaster Amplification",
        description: "Sends a small isMaster command to exposed MongoDB instances. Response includes server status, replica set config, and available commands. Typically 500-2000 bytes. Amplification via response size.",
        layer: NetworkLayer::Application,
        transport: TransportType::Udp,
        port: 27017,
        ampl_factor: "3-8x",
        needs_root: true,
        works_with_tor: false,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "docker-api",
        name: "Docker API Amplification",
        description: "Exposed Docker API endpoints respond with full system info (containers, images, volumes) to a small request. /info and /containers/json endpoints return large JSON payloads reflecting all Docker state.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 2375,
        ampl_factor: "10-100x",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "kerberos-as-req",
        name: "Kerberos AS-REQ Amplification",
        description: "Sends Kerberos Authentication Service requests (AS-REQ) to domain controllers. The server responds with TGT data (AS-REP) including encrypted session keys and PAC data. Response significantly larger than request.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 88,
        ampl_factor: "5-15x",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "postgres-md5-auth",
        name: "PostgreSQL MD5 Auth Flood",
        description: "Sends PostgreSQL startup packets with MD5 password authentication. Each attempt forces the server to compute MD5 hashes, look up users, and allocate backend processes. Memory and CPU amplification per connection.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 5432,
        ampl_factor: "5-15x per attempt",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "cassandra-thrift",
        name: "Cassandra Thrift Amplification",
        description: "Sends small Cassandra Thrift protocol requests. Responses include schema, token map, and node status information. Combined with wide-row reads, can produce significant response amplification.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 9042,
        ampl_factor: "5-10x",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "nfs-mountd",
        name: "NFS Mountd Dump Amplification",
        description: "Sends requests to NFS mountd (rpc.mountd) to list exported shares. The server responds with the full list of NFS exports and their options. Amplification depends on the number of configured exports.",
        layer: NetworkLayer::Application,
        transport: TransportType::Udp,
        port: 2049,
        ampl_factor: "3-8x",
        needs_root: true,
        works_with_tor: false,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "bacnet-device",
        name: "BACnet Device Discovery Amplification",
        description: "Sends BACnet Who-Is or ReadProperty requests to building automation devices. Each device responds with its full device object properties. Can enumerate all devices on a BACnet network from a single request.",
        layer: NetworkLayer::Application,
        transport: TransportType::Udp,
        port: 47808,
        ampl_factor: "3-8x per device",
        needs_root: false,
        works_with_tor: false,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "ard-query",
        name: "Apple Remote Desktop Query",
        description: "Sends Apple Remote Desktop (ARD) query packets to macOS machines. Each machine responds with system information, user list, and hardware details. Several hundred bytes response from a small request.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 3283,
        ampl_factor: "5-10x",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "openvpn-ping",
        name: "OpenVPN Ping Amplification",
        description: "Sends OpenVPN control channel pings to exposed VPN servers. The server responds with its TLS certificate, cipher list, and protocol options. Response can be 2-3x the request size.",
        layer: NetworkLayer::Application,
        transport: TransportType::Udp,
        port: 1194,
        ampl_factor: "2-3x",
        needs_root: true,
        works_with_tor: false,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "ike-amplification",
        name: "IPsec/IKE Amplification",
        description: "Sends IKE SA INIT packets to VPN gateways. The server responds with its supported transforms, DH groups, and certificate payloads. Response can be 2-5x larger than the initiating packet.",
        layer: NetworkLayer::Application,
        transport: TransportType::Udp,
        port: 500,
        ampl_factor: "2-5x",
        needs_root: true,
        works_with_tor: false,
        is_implemented: true,
        http_mode: None,
    },
    // ================================================================
    // TRIGGER-based amplification (Hybrid)
    // ================================================================
    AmplificationMethod {
        id: "cups-ipp-trigger",
        name: "CUPS/IPP UDP Trigger Amplification (CVE-2024-47176)",
        description: "Sends a small UDP packet to port 631 with a crafted IPP URI. The CUPS browsing daemon (cups-browsed) connects back to the specified URI, potentially triggering HTTP downloads or callback chains. Small trigger, potentially large downstream impact.",
        layer: NetworkLayer::Application,
        transport: TransportType::Hybrid,
        port: 631,
        ampl_factor: "10-100x (downstream chain)",
        needs_root: false,
        works_with_tor: false,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "webhook-chain",
        name: "Webhook/SSRF Trigger Chain",
        description: "Triggers a webhook that itself triggers more webhooks, creating a fan-out amplification effect. Each trigger multiplies downstream requests. Particularly effective against event-driven architectures (Zapier, IFTTT, GitHub Actions, etc.).",
        layer: NetworkLayer::Application,
        transport: TransportType::Hybrid,
        port: 443,
        ampl_factor: "5-50x per trigger",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "email-verification",
        name: "Email/SMS Verification Flood",
        description: "Triggers account registration or password reset flows that send verification emails or SMS messages. Each tiny API request causes an outbound email/SMS. Amplification is via service cost (SMS rates) and email infrastructure processing.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 443,
        ampl_factor: "Service-cost amplification",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "dns-recursive-chain",
        name: "Recursive DNS Chain Amplification",
        description: "Crafts DNS queries that trigger recursive resolution chains. A single query can cause multiple upstream DNS server lookups, each generating responses. Amplifies at each resolver hop.",
        layer: NetworkLayer::Application,
        transport: TransportType::Hybrid,
        port: 53,
        ampl_factor: "3-10x per chain hop",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: None,
    },
    // ================================================================
    // L4 TRANSPORT
    // ================================================================
    AmplificationMethod {
        id: "tcp-syn-flood",
        name: "TCP SYN Flood",
        description: "Sends many TCP SYN packets with spoofed source IPs. The server allocates TCB (Transmission Control Block) for each half-open connection, filling the SYN backlog queue. Classic denial of service at the transport layer.",
        layer: NetworkLayer::Transport,
        transport: TransportType::Raw,
        port: 0,
        ampl_factor: "Connection queue exhaustion",
        needs_root: true,
        works_with_tor: false,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "tcp-rst-flood",
        name: "TCP RST Flood",
        description: "Sends forged TCP RST packets to disrupt established connections. By guessing or observing sequence numbers, an attacker can tear down TCP connections between two hosts. Disrupts ongoing sessions.",
        layer: NetworkLayer::Transport,
        transport: TransportType::Raw,
        port: 0,
        ampl_factor: "Connection disruption",
        needs_root: true,
        works_with_tor: false,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "tcp-connection-flood",
        name: "TCP Connection Flood",
        description: "Completes many TCP three-way handshakes (full connections) but sends no data. Each connection consumes server file descriptors, memory for socket buffers, and kernel connection tracking entries.",
        layer: NetworkLayer::Transport,
        transport: TransportType::Tcp,
        port: 0,
        ampl_factor: "Resource exhaustion per connection",
        needs_root: false,
        works_with_tor: false,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "udp-flood",
        name: "UDP Flood",
        description: "Sends many UDP packets to random ports on the target. The server must process each packet, check for listening sockets, and potentially send ICMP unreachable responses. Pure bandwidth exhaustion at transport layer.",
        layer: NetworkLayer::Transport,
        transport: TransportType::Udp,
        port: 0,
        ampl_factor: "1x (pure bandwidth)",
        needs_root: false,
        works_with_tor: false,
        is_implemented: true,
        http_mode: None,
    },
    // ================================================================
    // L3 NETWORK
    // ================================================================
    AmplificationMethod {
        id: "icmp-smurf",
        name: "ICMP Smurf Amplification",
        description: "Sends ICMP Echo Request packets with spoofed source IP to a directed broadcast address. Every host on the broadcast network responds with an Echo Reply to the victim. Classic amplification from the 1990s, mitigated by no directed-broadcast configs.",
        layer: NetworkLayer::Network,
        transport: TransportType::Icmp,
        port: 0,
        ampl_factor: "1-Nx (N = hosts on network)",
        needs_root: true,
        works_with_tor: false,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "icmp-fragmentation",
        name: "ICMP Fragmentation Bomb",
        description: "Sends ICMP packets requiring fragmentation, or sends ICMP Fragment Needed messages to manipulate Path MTU Discovery. Forces server to fragment outgoing packets or reduce MSS, degrading throughput.",
        layer: NetworkLayer::Network,
        transport: TransportType::Icmp,
        port: 0,
        ampl_factor: "Performance degradation",
        needs_root: true,
        works_with_tor: false,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "ip-frag-overload",
        name: "IP Fragmentation Overload",
        description: "Sends many fragmented IP packets with overlapping or incomplete fragments. The server must allocate memory to reassemble fragments, waiting for missing packets. Exhausts kernel reassembly buffers.",
        layer: NetworkLayer::Network,
        transport: TransportType::Raw,
        port: 0,
        ampl_factor: "Memory exhaustion per fragment",
        needs_root: true,
        works_with_tor: false,
        is_implemented: true,
        http_mode: None,
    },
    // ================================================================
    // L2 DATA LINK
    // ================================================================
    AmplificationMethod {
        id: "arp-flood",
        name: "ARP Flood",
        description: "Sends many gratuitous ARP replies or ARP requests with spoofed MAC addresses. Switches learn fake MAC-IP bindings, flooding the CAM table and causing the switch to flood traffic to all ports. Disrupts local network operations.",
        layer: NetworkLayer::DataLink,
        transport: TransportType::Raw,
        port: 0,
        ampl_factor: "CAM table exhaustion",
        needs_root: true,
        works_with_tor: false,
        is_implemented: true,
        http_mode: None,
    },
    AmplificationMethod {
        id: "mac-flooding",
        name: "MAC Address Table Flood",
        description: "Floods a switch with frames from many different source MAC addresses. The switch's CAM table fills up, forcing it into fail-open mode (flooding all frames to all ports). Allows traffic sniffing and degrades network performance.",
        layer: NetworkLayer::DataLink,
        transport: TransportType::Raw,
        port: 0,
        ampl_factor: "Switch CAM table exhaustion",
        needs_root: true,
        works_with_tor: false,
        is_implemented: true,
        http_mode: None,
    },
    // ================================================================
    // NEW: TP240PhoneHome / CVE-2022-26143 (Cisco ISE) — UDP
    // Theoretical amplification: ~4.3 billion ×
    // ================================================================
    AmplificationMethod {
        id: "tp240-phonehome",
        name: "TP240PhoneHome / CVE-2022-26143 (Cisco ISE)",
        description: "CVE-2022-26143: Unauthenticated RCE on Cisco ISE appliances. TP240PhoneHome is a UDP-based amplification vector exploiting the ISE authentication service on port 443. The theoretical amplification factor reaches ~4.3 billion due to the small request triggering massive certificate chain responses. This is a critical zero-day class attack requiring root access for raw UDP transmission.",
        layer: NetworkLayer::Application,
        transport: TransportType::Udp,
        port: 443,
        ampl_factor: "~4,300,000,000x (theoretical)",
        needs_root: true,
        works_with_tor: false,
        is_implemented: true,
        http_mode: None,
    },
    // ================================================================
    // NEW: NXNSAttack / DNS NXNS — UDP
    // Amplification: ~1,620×
    // ================================================================
    AmplificationMethod {
        id: "dns-nxns-attack",
        name: "DNS NXNSAttack (DNS NX NS Attack)",
        description: "NXNSAttack exploits DNS delegation to achieve high amplification. By crafting queries that trigger NXDOMAIN responses with NS records, the attacker causes recursive resolvers to generate large responses. The attack exploits the gap between query size and the amplified response containing multiple NS records and additional section data.",
        layer: NetworkLayer::Application,
        transport: TransportType::Udp,
        port: 53,
        ampl_factor: "~1,620x",
        needs_root: true,
        works_with_tor: false,
        is_implemented: true,
        http_mode: None,
    },
    // ================================================================
    // NEW: HTTP/2 Rapid Reset (CVE-2023-44487) — HTTP/TCP
    // ================================================================
    AmplificationMethod {
        id: "h2-rapid-reset",
        name: "HTTP/2 Rapid Reset (CVE-2023-44487)",
        description: "CVE-2023-44487: HTTP/2 Rapid Reset Attack. By rapidly sending HEADERS frames followed by RST_STREAM frames, the attacker exhausts server resources during stream cancellation. Each request cancels the previous stream before any data is sent, but the server must allocate resources for each new stream. This causes a denial-of-service without needing to send significant data payloads.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 443,
        ampl_factor: "Connection resource exhaustion",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: Some("h2rapidreset"),
    },
    // ================================================================
    // NEW: Multi-Vector Carpet Bombing — HTTP/TCP
    // Orchestrates multiple HTTP attack vectors simultaneously
    // ================================================================
    AmplificationMethod {
        id: "carpet-bomb",
        name: "Multi-Vector Carpet Bombing",
        description: "Orchestrates multiple HTTP attack vectors simultaneously: HeaderBomb (massive headers), QueryFlood (query parameter floods), CookieBomb (cookie exhaustion), and AuthFlood (authentication attempts). Each sub-vector targets different resource categories of the target server — memory, CPU, connection pools, and session state — creating a comprehensive application-layer denial-of-service that exploits the server's inability to handle concurrent attack types.",
        layer: NetworkLayer::Application,
        transport: TransportType::Tcp,
        port: 443,
        ampl_factor: "Multi-vector compound exhaustion",
        needs_root: false,
        works_with_tor: true,
        is_implemented: true,
        http_mode: Some("carpetbomb"),
    },
];
