#[derive(Clone, Copy, PartialEq, Debug)]
pub enum ProxyMode { Scrape, Tor, ScrapeTorFallback }
impl std::fmt::Display for ProxyMode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self { ProxyMode::Scrape => write!(f, "Scrape"), ProxyMode::Tor => write!(f, "Tor"), ProxyMode::ScrapeTorFallback => write!(f, "Scrape→Tor") }
    }
}
impl ProxyMode {
    pub fn from_str(s: &str) -> Self {
        match s.to_ascii_lowercase().as_str() {
            "tor" => ProxyMode::Tor,
            "scrape-tor" => ProxyMode::ScrapeTorFallback,
            _ => ProxyMode::Scrape,
        }
    }
}

#[derive(Clone, Copy, PartialEq, Debug)]
pub enum AttackMode { Bandwidth, SlowRead, ImageOpt, LargePost, AssetSpray, RangeReq, CookieBomb, Ssr, Middleware, RequestFlood, Normal, NotFound, Slowloris, HeaderBomb, QueryFlood, DeepPath, AuthFlood,
    CacheBypass, FormMulti, XmlBomb, GraphqlFlood, RedirectLoop, EmptyBody,
    ChunkedFlood, TrailHeaders, ConnectionClose, Expect100, VaryFlood, DeflateBomb,
    TraceAmplify, HostPoison, ConditionalFlood, CorsFlood, PutFlood, DeleteFlood,
    SessionFlood, ContentTypeFlood, UpgradeAmplify,
    HeadFlood, OptionsFlood, PatchFlood, SlowPost, JsonBomb,
    ContentNegotiate, PreferFlood, RangeOverlap, MultiPost, CspReport,
    ConnectFlood, KeepAliveFlood, LinkFlood, ForwardedFlood, HealthFlood,
    JwtExplode, UploadFlood, GraphqlIntrospect, AdminFlood, ParamFlood,
    TEFlood, WantDigestFlood, SaveDataFlood, SecFetchFlood, CsvBomb,
    SerializedBomb, WellKnownFlood, SwaggerFlood, LoginFlood, MethodOverrideFlood,
    CookieBomb2, GraphqlBatch, WebhookFlood, ApiVersionFlood,
    PrototypeFlood, JsonpFlood, ArrayFlood, SitemapFlood,
    UnicodeFlood, ParamDuplicate,
    CacheBusterFlood, FileEnumFlood, SoapFlood, SignedHeaderFlood,
    Utf8BomFlood, DoubleDotFlood, EmptyParamFlood, HeaderOrderFlood,
    CrossDomainFlood, RefererFlood,
}
impl std::fmt::Display for AttackMode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            AttackMode::Bandwidth => write!(f, "Bandwidth"),
            AttackMode::SlowRead => write!(f, "Slow Read"),
            AttackMode::ImageOpt => write!(f, "Image Opt"),
            AttackMode::LargePost => write!(f, "Large POST"),
            AttackMode::AssetSpray => write!(f, "Asset Spray"),
            AttackMode::RangeReq => write!(f, "Range Req"),
            AttackMode::CookieBomb => write!(f, "Cookie Bomb"),
            AttackMode::Ssr => write!(f, "SSR"),
            AttackMode::Middleware => write!(f, "Middleware"),
            AttackMode::RequestFlood => write!(f, "Request Flood"),
            AttackMode::Normal => write!(f, "Normal"),
            AttackMode::NotFound => write!(f, "404 Storm"),
            AttackMode::Slowloris => write!(f, "Slowloris"),
            AttackMode::HeaderBomb => write!(f, "Header Bomb"),
            AttackMode::QueryFlood => write!(f, "Query Flood"),
            AttackMode::DeepPath => write!(f, "Deep Path"),
            AttackMode::AuthFlood => write!(f, "Auth Flood"),
            AttackMode::CacheBypass => write!(f, "Cache Bypass"),
            AttackMode::FormMulti => write!(f, "Form Multi"),
            AttackMode::XmlBomb => write!(f, "XML Bomb"),
            AttackMode::GraphqlFlood => write!(f, "GraphQL Flood"),
            AttackMode::RedirectLoop => write!(f, "Redirect Loop"),
            AttackMode::EmptyBody => write!(f, "Empty Body"),
            AttackMode::ChunkedFlood => write!(f, "Chunked Flood"),
            AttackMode::TrailHeaders => write!(f, "Trail Headers"),
            AttackMode::ConnectionClose => write!(f, "Connection Close"),
            AttackMode::Expect100 => write!(f, "Expect: 100-continue"),
            AttackMode::VaryFlood => write!(f, "Vary Flood"),
            AttackMode::DeflateBomb => write!(f, "Deflate Bomb"),
            AttackMode::TraceAmplify => write!(f, "Trace Amplify"),
            AttackMode::HostPoison => write!(f, "Host Poison"),
            AttackMode::ConditionalFlood => write!(f, "Conditional Flood"),
            AttackMode::CorsFlood => write!(f, "CORS Flood"),
            AttackMode::PutFlood => write!(f, "PUT Flood"),
            AttackMode::DeleteFlood => write!(f, "DELETE Flood"),
            AttackMode::SessionFlood => write!(f, "Session Flood"),
            AttackMode::ContentTypeFlood => write!(f, "Content-Type Flood"),
            AttackMode::UpgradeAmplify => write!(f, "Upgrade Amplify"),
            AttackMode::HeadFlood => write!(f, "HEAD Flood"),
            AttackMode::OptionsFlood => write!(f, "OPTIONS Flood"),
            AttackMode::PatchFlood => write!(f, "PATCH Flood"),
            AttackMode::SlowPost => write!(f, "Slow POST"),
            AttackMode::JsonBomb => write!(f, "JSON Bomb"),
            AttackMode::ContentNegotiate => write!(f, "Content Negotiate"),
            AttackMode::PreferFlood => write!(f, "Prefer Flood"),
            AttackMode::RangeOverlap => write!(f, "Range Overlap"),
            AttackMode::MultiPost => write!(f, "Multi POST"),
            AttackMode::CspReport => write!(f, "CSP Reports"),
            AttackMode::ConnectFlood => write!(f, "CONNECT Flood"),
            AttackMode::KeepAliveFlood => write!(f, "Keep-Alive Flood"),
            AttackMode::LinkFlood => write!(f, "Link Flood"),
            AttackMode::ForwardedFlood => write!(f, "Forwarded Flood"),
            AttackMode::HealthFlood => write!(f, "Health Flood"),
            AttackMode::JwtExplode => write!(f, "JWT Explode"),
            AttackMode::UploadFlood => write!(f, "Upload Flood"),
            AttackMode::GraphqlIntrospect => write!(f, "GraphQL Introspect"),
            AttackMode::AdminFlood => write!(f, "Admin Flood"),
            AttackMode::ParamFlood => write!(f, "Param Flood"),
            AttackMode::TEFlood => write!(f, "TE Flood"),
            AttackMode::WantDigestFlood => write!(f, "Want-Digest Flood"),
            AttackMode::SaveDataFlood => write!(f, "Save-Data Flood"),
            AttackMode::SecFetchFlood => write!(f, "Sec-Fetch Flood"),
            AttackMode::CsvBomb => write!(f, "CSV Bomb"),
            AttackMode::SerializedBomb => write!(f, "Serialized Bomb"),
            AttackMode::WellKnownFlood => write!(f, "Well-Known Flood"),
            AttackMode::SwaggerFlood => write!(f, "Swagger Flood"),
            AttackMode::LoginFlood => write!(f, "Login Flood"),
            AttackMode::MethodOverrideFlood => write!(f, "Method Override Flood"),
            AttackMode::CookieBomb2 => write!(f, "Cookie Bomb 2"),
            AttackMode::GraphqlBatch => write!(f, "GraphQL Batch"),
            AttackMode::WebhookFlood => write!(f, "Webhook Flood"),
            AttackMode::ApiVersionFlood => write!(f, "API Version Flood"),
            AttackMode::PrototypeFlood => write!(f, "Prototype Pollution Flood"),
            AttackMode::JsonpFlood => write!(f, "JSONP Flood"),
            AttackMode::ArrayFlood => write!(f, "Array Flood"),
            AttackMode::SitemapFlood => write!(f, "Sitemap Flood"),
            AttackMode::UnicodeFlood => write!(f, "Unicode Flood"),
            AttackMode::ParamDuplicate => write!(f, "Param Duplicate"),
            AttackMode::CacheBusterFlood => write!(f, "Cache Buster Flood"),
            AttackMode::FileEnumFlood => write!(f, "File Enum Flood"),
            AttackMode::SoapFlood => write!(f, "Soap Flood"),
            AttackMode::SignedHeaderFlood => write!(f, "Signed Header Flood"),
            AttackMode::Utf8BomFlood => write!(f, "UTF-8 BOM Flood"),
            AttackMode::DoubleDotFlood => write!(f, "Double Dot Flood"),
            AttackMode::EmptyParamFlood => write!(f, "Empty Param Flood"),
            AttackMode::HeaderOrderFlood => write!(f, "Header Order Flood"),
            AttackMode::CrossDomainFlood => write!(f, "Cross Domain Flood"),
            AttackMode::RefererFlood => write!(f, "Referer Flood"),
        }
    }
}
impl AttackMode {
    pub fn from_str(s: &str) -> Self {
        match s.to_ascii_lowercase().as_str() {
            "bandwidth" => AttackMode::Bandwidth,
            "slowread" => AttackMode::SlowRead,
            "imageopt" => AttackMode::ImageOpt,
            "largepost" => AttackMode::LargePost,
            "assetspray" => AttackMode::AssetSpray,
            "rangereq" => AttackMode::RangeReq,
            "cookiebomb" => AttackMode::CookieBomb,
            "ssr" => AttackMode::Ssr,
            "middleware" => AttackMode::Middleware,
            "requestflood" => AttackMode::RequestFlood,
            "notfound" => AttackMode::NotFound,
            "slowloris" => AttackMode::Slowloris,
            "headerbomb" => AttackMode::HeaderBomb,
            "queryflood" => AttackMode::QueryFlood,
            "deeppath" => AttackMode::DeepPath,
            "authflood" => AttackMode::AuthFlood,
            "cachebypass" => AttackMode::CacheBypass,
            "formmulti" => AttackMode::FormMulti,
            "xmlbomb" => AttackMode::XmlBomb,
            "graphqlflood" => AttackMode::GraphqlFlood,
            "redirectloop" => AttackMode::RedirectLoop,
            "emptybody" => AttackMode::EmptyBody,
            "chunkedflood" => AttackMode::ChunkedFlood,
            "trailheaders" => AttackMode::TrailHeaders,
            "connectionclose" => AttackMode::ConnectionClose,
            "expect100" => AttackMode::Expect100,
            "varyflood" => AttackMode::VaryFlood,
            "deflatebomb" => AttackMode::DeflateBomb,
            "traceamplify" => AttackMode::TraceAmplify,
            "hostpoison" => AttackMode::HostPoison,
            "conditionalflood" => AttackMode::ConditionalFlood,
            "corsflood" => AttackMode::CorsFlood,
            "putflood" => AttackMode::PutFlood,
            "deleteflood" => AttackMode::DeleteFlood,
            "sessionflood" => AttackMode::SessionFlood,
            "contenttypeflood" => AttackMode::ContentTypeFlood,
            "upgradeamplify" => AttackMode::UpgradeAmplify,
            "headflood" => AttackMode::HeadFlood,
            "optionsflood" => AttackMode::OptionsFlood,
            "patchflood" => AttackMode::PatchFlood,
            "slowpost" => AttackMode::SlowPost,
            "jsonbomb" => AttackMode::JsonBomb,
            "contentnegotiate" => AttackMode::ContentNegotiate,
            "preferflood" => AttackMode::PreferFlood,
            "rangeoverlap" => AttackMode::RangeOverlap,
            "multipost" => AttackMode::MultiPost,
            "cspreports" => AttackMode::CspReport,
            "connectflood" => AttackMode::ConnectFlood,
            "keepaliveflood" => AttackMode::KeepAliveFlood,
            "linkflood" => AttackMode::LinkFlood,
            "forwardedflood" => AttackMode::ForwardedFlood,
            "healthflood" => AttackMode::HealthFlood,
            "jwtexplode" => AttackMode::JwtExplode,
            "uploadflood" => AttackMode::UploadFlood,
            "graphqlintrospect" => AttackMode::GraphqlIntrospect,
            "adminflood" => AttackMode::AdminFlood,
            "paramflood" => AttackMode::ParamFlood,
            "teflood" => AttackMode::TEFlood,
            "wantdigestflood" => AttackMode::WantDigestFlood,
            "savedataflood" => AttackMode::SaveDataFlood,
            "secfetchflood" => AttackMode::SecFetchFlood,
            "csvbomb" => AttackMode::CsvBomb,
            "serializedbomb" => AttackMode::SerializedBomb,
            "wellknownflood" => AttackMode::WellKnownFlood,
            "swaggerflood" => AttackMode::SwaggerFlood,
            "loginflood" => AttackMode::LoginFlood,
            "methodoverrideflood" => AttackMode::MethodOverrideFlood,
            "cookiebomb2" => AttackMode::CookieBomb2,
            "graphqlbatch" => AttackMode::GraphqlBatch,
            "webhookflood" => AttackMode::WebhookFlood,
            "apiversionflood" => AttackMode::ApiVersionFlood,
            "prototypeflood" => AttackMode::PrototypeFlood,
            "jsonpflood" => AttackMode::JsonpFlood,
            "arrayflood" => AttackMode::ArrayFlood,
            "sitemapflood" => AttackMode::SitemapFlood,
            "unicodeflood" => AttackMode::UnicodeFlood,
            "paramduplicate" => AttackMode::ParamDuplicate,
            "cachebusterflood" => AttackMode::CacheBusterFlood,
            "fileenumflood" => AttackMode::FileEnumFlood,
            "soapflood" => AttackMode::SoapFlood,
            "signedheaderflood" => AttackMode::SignedHeaderFlood,
            "utf8bomflood" => AttackMode::Utf8BomFlood,
            "doubledotflood" => AttackMode::DoubleDotFlood,
            "emptyparamflood" => AttackMode::EmptyParamFlood,
            "headerorderflood" => AttackMode::HeaderOrderFlood,
            "crossdomainflood" => AttackMode::CrossDomainFlood,
            "refererflood" => AttackMode::RefererFlood,
            _ => AttackMode::Normal,
        }
    }
}
